### ISSUE TITLE
탭바 만들기

### ISSUE THREAD

**Issue by myhan601** [suri0000/PopDangSquare#10]
## 🛠️ 작업 목적

각 페이지를 이동할 수 있는 탭바를 제작합니다

## 📝 To-do
- [x] 기본 탭바를 구현합니다 
- [x] 탭별 스토리보드 연결을 합니다
- [ ] 커스텀 탭바를 구현합니다
- [ ] 가운데 커스텀 버튼을 배치합니다
- [ ] 탭바 가운데에 버튼으로 "예매하기"버튼을 만듭니다 -> 기능구현은 추후

### 참고 사항

홈 - MainPage
검색 - SearchPage
예매하기 - DetailView(임시로 했습니다)
마이페이지 - MyPage

중간 머지후에 작업할 예정입니다
커스텀 탭바는 진행 속도에 따라서 변경될 수 있습니다

MainPage, SearchPage, DetailView, MyPage 하단에 TabBar아이템을 추가했습니다

**Comment by suri0000** [comment]
철희님 브랜치 이름이 컨벤션과 다릅니다! 컨벤션 참고해서 브랜치 이름 수정해주세요. #이 모두 빠졌습니다

**Comment by myhan601** [comment]
브랜치 수정했습니다!
