### ISSUE TITLE
기본 마이페이지 기능 만들기

### ISSUE THREAD

**Issue by Neo-agnes** [suri0000/PopDangSquare#11]
## 🛠️ 작업 목적
마이페이지와의 연결과 기능을 만듭니다.

## 📝 To-do
UI 구현
- [x] 내정보 수정 뷰 구현
- [x] 예매내역 확인 뷰 구현
- [x] 아이콘추가

기능 구현
- [x] 로그인기능에서 회원 데이터 받아오기 (진행예정-예슬님과 협업)
- [x] 로그인 데이터 수정 후 수정 데이터 전송 기능 구현 (위에가 되면 진행)

### 참고 사항
지속 업데이트... 예정...?

**Comment by suri0000** [comment]
지금 보기에 준영님의 이슈단위가 너무 큰 것 같습니다. 이슈 단위를 작게 가져가고 PR을 자주 올리기로 했으니 UI 작업까지만 해서 PR을 올려주시고 기능부분은 새로운 이슈를 파는 건 어떨까요?

**Comment by Neo-agnes** [comment]
어... 그러기엔 시간이 부족할 것 같아서...

**Comment by Neo-agnes** [comment]
일단은 크게 잡은 부분이 된 것 같습니다...

**Comment by suri0000** [comment]
그러기에 시간이 부족할 것 같다는 말이 잘 이해가 안 됩니다..해야할 일의 양은 똑같고, 단지 일을 나눠서 이슈를 새로 파는 건데 왜 시간이 부족하다는 걸까요..? 제가 이해를 잘못한 걸까요?😅
