### ISSUE TITLE
로그인 구현하기

### ISSUE THREAD

**Issue by suri0000** [suri0000/PopDangSquare#2]
## 🛠️ 작업 목적

로그인과 회원가입을 구현합니다.

## 📝 To-do
- [x] 로고 이미지 추가
- [x] 아이디, 패스워드, 로그인 버튼 UI
- [x] 간편로그인, 회원가입 UI
- [x] 회원가입 UI
- [x] 아이디, 비밀번호, 이름 유효성 검사
- [x] 가입 데이터 저장

**Comment by Neo-agnes** [comment]
예시의 중요성 ....

**Comment by suri0000** [comment]
🥲
