### ISSUE TITLE
메인페이지 UI다듬기

### ISSUE THREAD

**Issue by myhan601** [suri0000/PopDangSquare#22]
## 🛠️ 작업 목적

메인페이지의 컬렉션뷰셀, 테이블뷰 등 전박적인 UI를 수정합니다

## 📝 To-do
- [x] 오토레이아웃을 잡습니다
- [x] 필요한 `Label`을 추가합니다
- [x] '에매하기' 버튼눌렀을 때 DetailView로 전환합니다
- [x] PageControl의 위치를 좌측 상단으로 변경합니다
- [x] PageControl 위치 좌측 상단으로 변경
- [x] 셀의 크기 조정 
- [x] 뷰컨트롤러의 배경색이 보이도록 조정
- [x] 가로스크롤 구현할것

### 참고 사항

추후 실제 데이터가 들어가면 다시 수정을 해야할 수도 있습니다
DetailView전환은 현재 모달로 되고있습니다
각 셀간의 간격 조정이 좀더 필요합니다

**Comment by suri0000** [comment]
내용을 화면 구역별로 나눠서 작성해주신 것은 좋습니다! 그렇지만  ---, ComingSoon 과 같은 것들은 체크박스로 하지 않는 것이 좋아보여요. 체크박스의 개수가 곧 테스크의 개수가 되기 때문에 체크박스가 체크된 것 기준으로 철희님의 진행상황이 파악됩니다. 체크 박스가 많다는 건 할 일이 많다는 것이고, 이슈를 누르지 않고 봤을 때 체크가 어렵습니다.

**Comment by myhan601** [comment]
감사합니다.. 수정하겠습니다!

**Comment by myhan601** [comment]
브랜치 수정했습니다!
