### ISSUE TITLE
영화 예매 입력 페이지 구현

### ISSUE THREAD

**Issue by kimminung** [suri0000/PopDangSquare#23]
## 🛠️ 작업 목적

영화입력페이지 UI구성 예정

## 📝 To-do
- [x] 컬렉션뷰 시간/날짜 셀 작업
- [x] 배경 및 이미지뷰 작업
- [x] 레이블 작업
- [x] 취소/예매하기 스텍뷰
- [x] 취소/예매하기 모달 액션
- [x] 인원선택 UI 구성
- [ ] 인원선택 1종류당 1개만 선택되도록
- [ ] 초기화

### 참고 사항
모달은 아직 미구현

**Comment by suri0000** [comment]
이번 이슈는 잘 작성해주신 것 같습니다 민웅님! ☺️
