### ISSUE TITLE
검색페이지 UI 수정

### ISSUE THREAD

**Issue by myhan601** [suri0000/PopDangSquare#24]
## 🛠️ 작업 목적

SearchPage의 UI를 수정합니다

## 📝 To-do
- [x] 현재 테이블뷰+컬렉션뷰로 되어있는 부분을 테이블뷰로만 구현합니다
- [x] 추천영화를 보여주는 테이블뷰를 추가합니다
- [x] 위 테이블뷰에 들어갈 셀을 구현합니다
- [x] 검색결과를 보여주는 테이블뷰셀을 구현합니다

### 참고 사항

추후에 데이터가 들어오면 수정할 부분이 많을거같습니다

**Comment by suri0000** [comment]
굿굿👍

**Comment by myhan601** [comment]
브랜치 이름 수정했습니다!
