### ISSUE TITLE
마이페이지

### ISSUE THREAD

**Issue by Neo-agnes** [suri0000/PopDangSquare#3]
## 🛠️ 작업 목적
 마이페이지를 구현합니다.

## 📝 To-do
-- 로그인 상태의 UI 제작
- [x] 프로필 UI 
- [x] Quick menu UI
- [x] customer service center menu UI

-- 로그아웃 상태의 UI 제작
- [ ] 프로필 UI 
- [ ] Quick menu UI
- [ ] customer service center menu UI

-- Code Structure
- [ ] 프로필 Code 정의 및 구현
- [ ] Quick menu Code 정의 및 구현
- [ ] customer service center menu Code 정의 및 구현
- [ ] 연결 Code 구현

### 참고 사항
회고를 통한 추가사항 전달 예정

**Comment by suri0000** [comment]
준영님 '마이페이지 내'는 빼주셔도 됩니다!ㅋㅋㅋㅋ 마이페이지와 관련된 이슈라 안 적어주셔도 알겁니다ㅋㅋㅋㅋ
UI 제작 단위는 영역(?)별로 작성해주시는게 보기 편하다고 생각합니다! 예를 들어 준영님은 마이페이지를 맡으셨으니, 프로필 UI, Quick Menu UI ..등등 이런식으로 작성해주시면 좋을 것 같습니다! 물론 커밋은 자잘한 단위로 하면 좋지만 버튼 하나 추가할 때마다 커밋하기는 귀찮으니까요ㅎ
그리고 UI 작업 후 로직 작업예정이시라면 그건 또 투두로 작성해주셔도 좋을 것 같아요

**Comment by Neo-agnes** [comment]
넵~! 피드백 감사합니다~!

**Comment by Neo-agnes** [comment]
칭찬받았다 -행복 😆-
