### ISSUE TITLE
MainPage에 데이터 연결하기

### ISSUE THREAD

**Issue by myhan601** [suri0000/PopDangSquare#33]
## 🛠️ 작업 목적

TMDB Api를 활용해 데이터를 불러와서 UI에 적용합니다

## 📝 To-do
- [x] TMDB Api 연결하기
- [x] 받은 데이터 저장할 Model 작성하기 (현재 상영중, 무비차트, ComingSoon에 맞게?)
- [x] 용도에 맞게 모델의 프로퍼티 작성
- [x] 올바른 데이터를 받아오는지 확인
- [x] 데이터를 Ui에 적용하기

### 참고 사항

어떤 데이터를 받아와서 사용할지 더 구체적으로 생각해야 합니다
다른 페이지와 연결되면서 넘겨주는것도 고려해야할거같습니다
