### ISSUE TITLE
영화 상세페이지 데이터 받아오기

### ISSUE THREAD

**Issue by suri0000** [suri0000/PopDangSquare#34]
## 🛠️ 작업 목적
영화 상세페이지를 구성할 데이터를 받아옵니다

## 📝 To-do
- [x] 영화 기본 정보 데이터 모델 만들기
- [x] 영화 기본 정보 데이터 받아오기
- [x] 영화 기본 정보 데이터 보여주기
- [ ] 메인의 영화데이터를 받아서 영화진흥위원회 API에서 영화 코드 찾기
- [ ] 찾은 영화 코드를 통해 영화 기본 정보 데이터 보여주기
- [ ] 리뷰 데이터 모델 만들기
- [ ] 감독/배우 데이터 모델 만들기
- [ ] 영화진흥위원회 API에서 예매하기에서 넘어온 데이터와 비교하여 일치하는 영화제목의 영화코드 찾기
- [x] 줄거리 보여주기
- [ ] 감독/배우 보여주기
- [ ] 리뷰 보여주기
- [x] 포스터 보여주기

### 참고 사항

- 영화 리뷰와 줄거리 말고는 영화진흥위원회 API를 사용해야 합니다.
- 영화진흥위원회 API에서 감독과 배우의 이름은 제공하지만 사진은 제공하지 않고 있습니다.
- 현재 영화 기본 정보 데이터를 보여줄 수는 있지만, 예매하기 버튼을 눌렀을 때 넘어오는 데이터를 사용하고 있지 않습니다. (임의의 영화코드 사용중)
- 줄거리는 메인의 데이터를 이용중입니다.
