### ISSUE TITLE
검색페이지 데이터 연동, 화면 전환

### ISSUE THREAD

**Issue by myhan601** [suri0000/PopDangSquare#37]
## 🛠️ 작업 목적

검색페이지 테이블뷰 셀에 데이터를 연동합니다

## 📝 To-do
- [x] `RecommendCell`에 들어갈 이미지를 Popular에서 가져옵니다
- [x] 검색 결과에 맞는 영화 title을 찾아서 셀에 맞는 이미지를 넣어줍니다
- [x] 예매하기 버튼 눌렀을 때 DetailView로 화면을 전환합니다
- [x] 구경하기 버튼 눌렀을 때 DetailView로 화면을 전환합니다

### 참고 사항
#33 머지후에 작업할 예정입니다
검색 결과에 따른 데이터를 띄우는 로직을 구현해야합니다
예매하기 버튼은 추후 DetialView가 아닌 다른 페이지로 연결해야합니다.
