### ISSUE TITLE
상세페이지

### ISSUE THREAD

**Issue by kimminung** [suri0000/PopDangSquare#4]
## 🛠️ 작업 목적
상세페이지를 구현합니다.

## 📝 To-do
- [x] 영화 정보용 셀 구현(snpshot과 Diffable 활용)
- [x] 영화정보셀의 이미지와 레이블 구도 잡음
- [x] 실관람평용 추가 셀 배치 성공(Diffable에 XIB 셀 파일 케이스별 배치 방법 사용)

### 참고 사항
불러오기 작업부터 시작합니다.

**Comment by suri0000** [comment]
브랜치 하나는 제가 삭제할게요ㅋㅋㅋ 투두에서 '상세페이지'는 빼주셔도 됩니다! 상세페이지 관련 이슈라서 상세페이지인 걸 다 알겁니다ㅋㅋㅋ
투두 하나가 커밋의 단위가 좋기때문에 지금처럼 한국이름, 영문이름 등 너무 자세하게는 안 적으셔도 돼요! 한국이름 하나 적고 커밋하기는 귀찮잖아요? 예를 들면 영화 제목과 포스터 부분 UI, 실관람평 UI 등 이런식으로 섹션별로 해주시는 것도 좋을 것 같습니다~
