### ISSUE TITLE
메인 페이지

### ISSUE THREAD

**Issue by myhan601** [suri0000/PopDangSquare#5]
## 🛠️ 작업 목적

메인페이지를 구현합니다

## 📝 To-do
- [x] 메인 화면 틀 제작 `UIScrollView`활용
- [x] 최상단에 로고 이미지 첨부 
- [x] 나머지 밑의 요소들은 `StackView` + `UICollectionView`로 구현
- [x] `현재 상영중`은 `UICollectionViewCell`구현 -> 영화 포스터, 영화 이름, 상영시간, 예매율, 간략한 설명 나타내는 `label`
- [x] 추가로 `예매하기` 버튼 구현 -> 상세 페이지로 연결
- [x] `무비차트`는 아직 구현방식은 미정. 포스터를 보여주고 자동으로 넘어가는 식으로 구현 예정
- [x] `상영예정`은 곧 개봉할 영화들 보여주기 이것 또한 방식은 아직 미정

### 참고 사항

아직 구현 방식이 애매한 부분이 있습니다.
개인 학습하여 내용 보충하고 작업하겠습니다

**Comment by suri0000** [comment]
'메인페이지 내'를 유일하게 안 적어주신 철희님! 어떤 기술을 활용할지 적어주시는 것도 좋지만 귀찮으시면 안 적어주셔도 됩니다~ 
지금 투두가 거의 로직 구현 위주로 작성되어 있는데 UI 작업 관련 투두도 작성해주시면 더 좋을 것 같아요! 
투두 하나를 적절한 커밋 하나의 단위로 잘 작성해 주신 것 같습니다!

**Comment by myhan601** [comment]
무비차트와 상영예정은 일단 가로스크롤만 되도록 구현했습니다
예매하기 버튼의 다음 페이지 연결은 가상의 코드만 작성했습니다
