### ISSUE TITLE
전반적인 수정

### ISSUE THREAD

**Issue by myhan601** [suri0000/PopDangSquare#51]
## 🛠️ 작업 목적

메인 페이지, 검색페이지의 UI를 수정합니다!

## 📝 To-do
- [x] 무비차트셀에서 컬렉션뷰에 그림자를 추가합니다
- [ ] label과 셀간의 간격을 조정합니다
- [ ] 무비차트와 상영예정의 간격을 조정합니다
- [x] 서치바에 그림자를 넣습니다

### 참고 사항

앞선 pr들이 끝난후에 작업을 하겠습니다
추가적인 아이디어를 받으면 반영하겠습니다!
