### ISSUE TITLE
검색 페이지

### ISSUE THREAD

**Issue by myhan601** [suri0000/PopDangSquare#6]
## 🛠️ 작업 목적

영화 검색 페이지를 구현합니다

## 📝 To-do
**ui관련 작업**
- [x] 배경화면 색상 변경
- [x] `searchbar` 뷰 상단에 추가하기 (논의 후 작업 예정)
- [x] 서치바 하단에 "...으로 검색된 결과입니다" 띄워주기 -> ...부분은 서치바에 입력된 텍스트
- [x] 검색결과에 해당하는 셀?뷰? 하단에 띄우기
- [x] 위 셀에 "예매하기" 버튼

### 참고 사항

아직 생각중인 부분이 있어서 추후 수정하겠습니다
