### ISSUE TITLE
기본 로그인 기능 만들기

### ISSUE THREAD

**Issue by suri0000** [suri0000/PopDangSquare#7]
## 🛠️ 작업 목적
기본 로그인 기능을 만듭니다.

## 📝 To-do
- [x] 회원가입시 정보저장
- [x] 가입하기에서 회원정보 데이터 받아오기
- [x] 로그인 버튼 동작 구현
- [x] 자동 로그인 버튼 만들기
- [x] 자동 로그인 설정
- [x] 네비게이션 연결

### 참고 사항
애플 로그인은 나중에 할 예정입니다. (새로운 이슈)
