### ISSUE TITLE
상세페이지 추가 레이아웃 및 네트워킹파트

### ISSUE THREAD

**Issue by kimminung** [suri0000/PopDangSquare#8]
## 🛠️ 작업 목적

상세페이지 남은 섹션 구현 및 레이아웃 잡기 (출연배우와 감독 섹션, 트레일러 섹션)
네트워크 매니저 구현 예정

## 📝 To-do
- [ ] 줄거리용 공간 확보 및 ...더보기 구현 예정
- [ ] 섹션명을 담아줄 레이아웃 구현중
- [ ] 추가적으로 출연배우와 감독이 보이는 셀 구현중
- [ ] 마지막부분의 트레일러 영상용 셀 마련중
- [ ] Json데이터를 불러와서 담을 네트워킹 요령에 시간소요 예정
- [ ] 찜하기 버튼 생성(별모양)
